// CAR PULL: High-Fidelity Mock Data (Lagos Ajah -> VI -> Marina Corridor)
// Location: /src/lib/mockData.ts

import { SafeZone, CorridorDriver, EmergencyProvider, User, WaitingRider, TrafficAlert } from './types';

export const mockCurrentUser: User = {
  id: 'usr-current-001',
  phoneNumber: '+234 813 892 4110',
  email: 'femi.adeyemi@dangote.com',
  fullName: 'Femi Adeyemi',
  avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80',
  gender: 'male',
  bvnHash: 'bvn_9921_verified_hash_2026',
  ninHash: 'nin_8812_verified_hash_2026',
  kycStatus: 'verified',
  isFemaleCommuteOnly: false,
  employer: 'Dangote Group',
  employerDomain: 'dangote.com',
  alumniTag: 'University of Lagos',
  communityEstateName: 'Victoria Garden City (VGC)',
  saasSubscriptionActive: true,
  ratingScore: 4.97,
  tripsCompleted: 64,
  escrowBalanceNgn: 45000,
};

export const mockSafeZones: SafeZone[] = [
  {
    id: 'sz-1',
    name: 'TotalEnergies Mega Station',
    zone_type: 'fuel_station',
    address: 'Opposite Jakande Roundabout, Lekki-Epe Expressway',
    coordinates: { lat: 6.4428, lng: 3.5186 },
    is_active: true,
  },
  {
    id: 'sz-2',
    name: 'Circle Mall Parking Bay',
    zone_type: 'shopping_mall',
    address: 'Jakande, Lekki, Lagos',
    coordinates: { lat: 6.4389, lng: 3.5122 },
    is_active: true,
  },
  {
    id: 'sz-3',
    name: 'VGC Main Gate Security Bay',
    zone_type: 'gated_estate_gate',
    address: 'Victoria Garden City, Lekki-Epe Expressway',
    coordinates: { lat: 6.4552, lng: 3.5594 },
    is_active: true,
  },
  {
    id: 'sz-4',
    name: 'Mobil Sandfill Station Bay',
    zone_type: 'fuel_station',
    address: 'Sandfill Bus Stop, Lekki Phase 1, Lagos',
    coordinates: { lat: 6.4312, lng: 3.4510 },
    is_active: true,
  },
  {
    id: 'sz-5',
    name: 'Palms Shopping Mall Forecourt',
    zone_type: 'shopping_mall',
    address: '1 Bisway St, Maroko, Lekki, Lagos',
    coordinates: { lat: 6.4345, lng: 3.4478 },
    is_active: true,
  },
  {
    id: 'sz-6',
    name: 'Access Bank HQ Secure Forecourt',
    zone_type: 'bank_premises',
    address: 'Danmole St, Victoria Island, Lagos',
    coordinates: { lat: 6.4290, lng: 3.4285 },
    is_active: true,
  },
];

export const mockCorridorDrivers: CorridorDriver[] = [
  {
    id: 'driver-101',
    name: 'Babatunde Adeleke',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    employer: 'Flutterwave',
    employer_domain: 'flutterwavego.com',
    alumni: 'Babcock University',
    rating: 4.95,
    trips_completed: 142,
    vehicle: {
      make: 'Toyota',
      model: 'Camry',
      year: 2021,
      color: 'Midnight Black',
      plate_number: 'APP-842-EY',
      category: 'sedan',
      drivetrain: 'FWD',
      has_ac: true,
    },
    corridor: {
      origin: 'Ajah Langbasa',
      destination: 'Victoria Island (Ademola Adetokunbo)',
      departure_time: '06:45 AM',
      available_seats: 3,
      fuel_split_ngn: 1500,
      ac_included: true,
      distance_km: 26.5,
    },
    vibe_tags: ['AC On', 'Silent Commute', 'No Food in Car'],
  },
  {
    id: 'driver-102',
    name: 'Chioma Okonkwo',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    employer: 'PwC Nigeria',
    employer_domain: 'pwc.com',
    alumni: 'University of Lagos',
    rating: 4.98,
    trips_completed: 89,
    vehicle: {
      make: 'Honda',
      model: 'CR-V',
      year: 2022,
      color: 'Deep Purple',
      plate_number: 'KJA-512-AB',
      category: 'suv',
      drivetrain: 'AWD',
      has_ac: true,
    },
    corridor: {
      origin: 'Sangotedo (Shoprite)',
      destination: 'Marina / CMS',
      departure_time: '06:15 AM',
      available_seats: 2,
      fuel_split_ngn: 2500,
      ac_included: true,
      distance_km: 32.0,
    },
    vibe_tags: ['Women-Only', 'Tech Talk', 'Chill Gospel/R&B'],
  },
  {
    id: 'driver-103',
    name: 'Tunde Balogun',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    employer: 'Kuda Technologies',
    employer_domain: 'kuda.com',
    alumni: 'Covenant University',
    rating: 4.92,
    trips_completed: 215,
    vehicle: {
      make: 'Hyundai',
      model: 'Tucson',
      year: 2020,
      color: 'Graphite Grey',
      plate_number: 'LND-399-FX',
      category: 'suv',
      drivetrain: 'FWD',
      has_ac: true,
    },
    corridor: {
      origin: 'VGC Main Gate',
      destination: 'Marina / Broad St',
      departure_time: '07:00 AM',
      available_seats: 3,
      fuel_split_ngn: 1800,
      ac_included: true,
      distance_km: 22.4,
    },
    vibe_tags: ['AC On', 'Podcasts', 'Luggage Space'],
  },
  {
    id: 'driver-104',
    name: 'Amara Nwosu',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=400&q=80',
    employer: 'Access Bank',
    employer_domain: 'accessbankplc.com',
    alumni: 'Pan-Atlantic University',
    rating: 4.99,
    trips_completed: 178,
    vehicle: {
      make: 'Mazda',
      model: 'CX-5',
      year: 2023,
      color: 'Soul Red',
      plate_number: 'EPE-812-BD',
      category: 'suv',
      drivetrain: 'AWD',
      has_ac: true,
    },
    corridor: {
      origin: 'Ikota Shopping Complex',
      destination: 'Victoria Island (Adeola Odeku)',
      departure_time: '06:30 AM',
      available_seats: 2,
      fuel_split_ngn: 2200,
      ac_included: true,
      distance_km: 19.8,
    },
    vibe_tags: ['AC On', 'FinTech Enthusiast', 'No Smoking'],
  },
  {
    id: 'driver-105',
    name: 'Babatunde Adeleke',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    employer: 'Flutterwave',
    employer_domain: 'flutterwavego.com',
    alumni: 'Babcock University',
    rating: 4.95,
    trips_completed: 142,
    vehicle: {
      make: 'Toyota',
      model: 'Camry',
      year: 2021,
      color: 'Midnight Black',
      plate_number: 'APP-842-EY',
      category: 'sedan',
      drivetrain: 'FWD',
      has_ac: true,
    },
    corridor: {
      origin: 'Victoria Island (Ademola Adetokunbo)',
      destination: 'Ajah Langbasa',
      departure_time: '05:45 PM',
      available_seats: 3,
      fuel_split_ngn: 1800,
      ac_included: true,
      distance_km: 26.5,
    },
    vibe_tags: ['AC On', 'Evening Winddown', 'Podcasts'],
  },
  {
    id: 'driver-106',
    name: 'Amara Nwosu',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=400&q=80',
    employer: 'Access Bank',
    employer_domain: 'accessbankplc.com',
    alumni: 'Pan-Atlantic University',
    rating: 4.99,
    trips_completed: 178,
    vehicle: {
      make: 'Mazda',
      model: 'CX-5',
      year: 2023,
      color: 'Soul Red',
      plate_number: 'EPE-812-BD',
      category: 'suv',
      drivetrain: 'AWD',
      has_ac: true,
    },
    corridor: {
      origin: 'Victoria Island (Adeola Odeku)',
      destination: 'Ikota / VGC Main Gate',
      departure_time: '06:15 PM',
      available_seats: 2,
      fuel_split_ngn: 2200,
      ac_included: true,
      distance_km: 19.8,
    },
    vibe_tags: ['AC On', 'Chill R&B', 'Women Preferred'],
  },
];

export const mockEmergencyProviders: EmergencyProvider[] = [
  {
    id: 'prov-501',
    name: 'Musbau Towing & Recovery Services',
    operator_name: 'Musbau Lawal',
    operator_photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    phone: '+234 803 291 0022',
    category: 'flatbed_tow',
    rating: 4.88,
    lasdri_id: 'LASDRI/2026/TK-8910',
    plate_number: 'JJJ-109-XZ',
    truck_type: 'Hydraulic Heavy Flatbed',
    distance_km: 3.4,
    traffic_eta_minutes: 14,
    flat_quote_ngn: 35000,
    equipment: ['Hydraulic Winch', 'Wheel Straps', 'OBD2 Scanner'],
    has_lasdri_verified: true,
    has_obd2_scanner: true,
    vehicle: { category: 'flatbed_tow' },
  },
  {
    id: 'prov-502',
    name: 'FastFix Mobile Bike Mechanic',
    operator_name: 'Sunday Kingsley',
    operator_photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    phone: '+234 812 400 9911',
    category: 'mechanic_bike',
    rating: 4.92,
    lasdri_id: 'LASDRI/2026/MC-4412',
    plate_number: 'EPE-441-QC',
    truck_type: 'Tooling Motorbike',
    distance_km: 1.8,
    traffic_eta_minutes: 8,
    flat_quote_ngn: 8000,
    equipment: ['Jumpstarter Battery Pack', '12V Tyre Inflator', 'OBD2 Scanner', 'Standard Tooling'],
    has_lasdri_verified: true,
    has_obd2_scanner: true,
    vehicle: { category: 'mechanic_bike' },
  },
  {
    id: 'prov-503',
    name: 'Lekki Toll Heavy Duty Rescue',
    operator_name: 'Chinedu Eze',
    operator_photo: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=400&q=80',
    phone: '+234 802 888 1234',
    category: 'wheel_lift_tow',
    rating: 4.75,
    lasdri_id: 'LASDRI/2026/TK-5120',
    plate_number: 'KJA-892-LM',
    truck_type: 'Wheel-Lift Underlift Tow',
    distance_km: 4.1,
    traffic_eta_minutes: 19,
    flat_quote_ngn: 28000,
    equipment: ['Wheel-Lift Boom', 'Safety Chains', 'Compressor'],
    has_lasdri_verified: true,
    has_obd2_scanner: false,
    vehicle: { category: 'wheel_lift_tow' },
  },
  {
    id: 'prov-504',
    name: 'Apex Radiator & Thermal Mobile Tech',
    operator_name: 'Rasheed Adebisi',
    operator_photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80',
    phone: '+234 814 332 9001',
    category: 'mechanic_bike',
    rating: 4.96,
    lasdri_id: 'LASDRI/2026/MC-9118',
    plate_number: 'AGL-220-GH',
    truck_type: 'Mobile Thermal Van',
    distance_km: 2.2,
    traffic_eta_minutes: 11,
    flat_quote_ngn: 12000,
    equipment: ['Coolant Pressure Tester', 'Heavy Duty Coolant 5L', 'OBD2 Scanner', 'Fan Relay Kit'],
    has_lasdri_verified: true,
    has_obd2_scanner: true,
    vehicle: { category: 'mechanic_bike' },
  },
];

export const mockCorridorRiders: WaitingRider[] = [
  {
    id: 'rider-201',
    name: 'Chioma Okoli',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    employer: 'Stanbic IBTC Bank',
    employer_domain: 'stanbicibtc.com',
    rating: 4.97,
    pickupSafeZone: mockSafeZones[1], // Circle Mall
    destination: 'Victoria Island (Ahmadu Bello Way)',
    departure_time: '06:45 AM',
    bidNgn: 2000,
    isFemaleOnly: false,
    notes: 'Heading to Stanbic HQ. Quiet rider, backpack only.',
    status: 'waiting',
  },
  {
    id: 'rider-202',
    name: 'Olumide Adeleke',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    employer: 'Flutterwave',
    employer_domain: 'flutterwavego.com',
    rating: 4.93,
    pickupSafeZone: mockSafeZones[0], // TotalEnergies Jakande
    destination: 'Marina / Broad St',
    departure_time: '07:00 AM',
    bidNgn: 1800,
    isFemaleOnly: false,
    notes: 'Laptop bag only. Work at Flutterwave engineering.',
    status: 'waiting',
  },
  {
    id: 'rider-203',
    name: 'Amina Bello',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=400&q=80',
    employer: 'KPMG Nigeria',
    employer_domain: 'kpmg.com',
    rating: 4.99,
    pickupSafeZone: mockSafeZones[2], // VGC Main Gate
    destination: 'Victoria Island (Ademola Adetokunbo)',
    departure_time: '06:30 AM',
    bidNgn: 2200,
    isFemaleOnly: true,
    notes: 'Senior Consultant at KPMG. Early morning commute.',
    status: 'waiting',
  },
  {
    id: 'rider-204',
    name: 'David Nwachukwu',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    employer: 'Dangote Group',
    employer_domain: 'dangote.com',
    rating: 4.88,
    pickupSafeZone: mockSafeZones[3], // Mobil Sandfill
    destination: 'Marina / CMS Outer Marina',
    departure_time: '07:15 AM',
    bidNgn: 1500,
    isFemaleOnly: false,
    notes: 'Corporate colleague at Dangote Marina office.',
    status: 'waiting',
  },
  {
    id: 'rider-205',
    name: 'Zainab Yusuf',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    employer: 'PwC Nigeria',
    employer_domain: 'pwc.com',
    rating: 4.96,
    pickupSafeZone: mockSafeZones[4], // Palms Shopping Mall
    destination: 'Victoria Island (Adeola Odeku)',
    departure_time: '06:40 AM',
    bidNgn: 2000,
    isFemaleOnly: false,
    notes: 'Senior associate at PwC. Looking for AC ride.',
    status: 'waiting',
  },
];

export const mockTrafficAlerts: TrafficAlert[] = [
  {
    id: 'alert-1',
    location: 'Lekki 1st Toll',
    status: 'heavy',
    delayMinutes: 20,
    message: 'Heavy bottleneck approaching Admiralty Toll; expect 20m slowdown.',
  },
  {
    id: 'alert-2',
    location: 'Sandfill Bus Stop',
    status: 'free_flow',
    delayMinutes: 0,
    message: 'Sandfill underpass clear and moving smoothly.',
  },
  {
    id: 'alert-3',
    location: 'Jakande Roundabout',
    status: 'free_flow',
    delayMinutes: 0,
    message: 'Road surface dry, zero flash flood ponding.',
  },
];
