// CAR PULL: High-Fidelity Mock Data (Lagos Ajah -> VI -> Marina Corridor)
// Location: /src/lib/mockData.ts

import { SafeZone, CorridorDriver, EmergencyProvider, User, WaitingRider, TrafficAlert, LagosLocation, CommuteRoute } from './types';

export const mockCurrentUser: User = {
  id: 'usr-current-001',
  phoneNumber: '+234 813 892 4110',
  email: 'femi.adeyemi@dangote.com',
  fullName: 'Femi Adeyemi',
  avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80',
  gender: 'male',
  bvnHash: 'bvn_9921_verified_hash_2026',
  ninHash: 'nin_8812_verified_hash_2026',
  kycStatus: 'verified',
  isFemaleCommuteOnly: false,
  employer: 'Dangote Group',
  employerDomain: 'dangote.com',
  alumniTag: 'University of Lagos',
  communityEstateName: 'Victoria Garden City (VGC)',
  saasSubscriptionActive: true,
  ratingScore: 4.97,
  tripsCompleted: 64,
  escrowBalanceNgn: 45000,
};

export const mockSafeZones: SafeZone[] = [
  {
    id: 'sz-1',
    name: 'TotalEnergies Mega Station',
    zone_type: 'fuel_station',
    address: 'Opposite Jakande Roundabout, Lekki-Epe Expressway',
    coordinates: { lat: 6.4428, lng: 3.5186 },
    is_active: true,
  },
  {
    id: 'sz-2',
    name: 'Circle Mall Parking Bay',
    zone_type: 'shopping_mall',
    address: 'Jakande, Lekki, Lagos',
    coordinates: { lat: 6.4389, lng: 3.5122 },
    is_active: true,
  },
  {
    id: 'sz-3',
    name: 'VGC Main Gate Security Bay',
    zone_type: 'gated_estate_gate',
    address: 'Victoria Garden City, Lekki-Epe Expressway',
    coordinates: { lat: 6.4552, lng: 3.5594 },
    is_active: true,
  },
  {
    id: 'sz-4',
    name: 'Mobil Sandfill Station Bay',
    zone_type: 'fuel_station',
    address: 'Sandfill Bus Stop, Lekki Phase 1, Lagos',
    coordinates: { lat: 6.4312, lng: 3.4510 },
    is_active: true,
  },
  {
    id: 'sz-5',
    name: 'Palms Shopping Mall Forecourt',
    zone_type: 'shopping_mall',
    address: '1 Bisway St, Maroko, Lekki, Lagos',
    coordinates: { lat: 6.4345, lng: 3.4478 },
    is_active: true,
  },
  {
    id: 'sz-6',
    name: 'Access Bank HQ Secure Forecourt',
    zone_type: 'bank_premises',
    address: 'Danmole St, Victoria Island, Lagos',
    coordinates: { lat: 6.4290, lng: 3.4285 },
    is_active: true,
  },
];

export const mockLagosLocations: LagosLocation[] = [
  {
    id: 'loc-ajah',
    name: 'Ajah Jubilee Bridge / Langbasa',
    area: 'Ajah / Eti-Osa',
    coordinates: { lat: 6.4678, lng: 3.5683 },
    nearestSafeZoneId: 'sz-3',
    isPopularPickup: true,
  },
  {
    id: 'loc-sangotedo',
    name: 'Sangotedo / Novare Mall Bay',
    area: 'Lekki-Epe Expressway',
    coordinates: { lat: 6.4800, lng: 3.6150 },
    nearestSafeZoneId: 'sz-3',
    isPopularPickup: true,
  },
  {
    id: 'loc-vgc',
    name: 'Victoria Garden City (VGC)',
    area: 'Lekki-Epe Expressway',
    coordinates: { lat: 6.4552, lng: 3.5594 },
    nearestSafeZoneId: 'sz-3',
    isPopularPickup: true,
  },
  {
    id: 'loc-ikota',
    name: 'Ikota Shopping Complex / Mega Chicken',
    area: 'Ikota / Lekki-Epe',
    coordinates: { lat: 6.4510, lng: 3.5450 },
    nearestSafeZoneId: 'sz-1',
    isPopularPickup: true,
  },
  {
    id: 'loc-chevron',
    name: 'Chevron Drive / Alternative Route',
    area: 'Lekki Peninsula',
    coordinates: { lat: 6.4485, lng: 3.5385 },
    nearestSafeZoneId: 'sz-1',
    isPopularPickup: true,
  },
  {
    id: 'loc-jakande',
    name: 'Jakande Roundabout / Circle Mall',
    area: 'Jakande / Lekki',
    coordinates: { lat: 6.4428, lng: 3.5186 },
    nearestSafeZoneId: 'sz-1',
    isPopularPickup: true,
  },
  {
    id: 'loc-agungi',
    name: 'Agungi Bus Stop',
    area: 'Lekki-Epe Expressway',
    coordinates: { lat: 6.4395, lng: 3.5012 },
    nearestSafeZoneId: 'sz-1',
    isPopularPickup: true,
  },
  {
    id: 'loc-igbo-efon',
    name: 'Igbo-Efon / Chisco Bus Stop',
    area: 'Lekki',
    coordinates: { lat: 6.4380, lng: 3.4885 },
    nearestSafeZoneId: 'sz-4',
    isPopularPickup: true,
  },
  {
    id: 'loc-ikate',
    name: 'Ikate Elegushi / Meadow Hall',
    area: 'Lekki Phase 1 Axis',
    coordinates: { lat: 6.4372, lng: 3.4750 },
    nearestSafeZoneId: 'sz-4',
    isPopularPickup: true,
  },
  {
    id: 'loc-lekki1',
    name: 'Lekki Phase 1 (Admiralty Way)',
    area: 'Lekki Phase 1',
    coordinates: { lat: 6.4420, lng: 3.4530 },
    nearestSafeZoneId: 'sz-4',
    isPopularPickup: true,
    isPopularDropoff: true,
  },
  {
    id: 'loc-sandfill',
    name: 'Mobil Sandfill / Maroko',
    area: 'Lekki / Victoria Island Approach',
    coordinates: { lat: 6.4312, lng: 3.4510 },
    nearestSafeZoneId: 'sz-4',
    isPopularPickup: true,
    isPopularDropoff: true,
  },
  {
    id: 'loc-vi-adetokunbo',
    name: 'Victoria Island (Ademola Adetokunbo / Eko Hotel)',
    area: 'Victoria Island',
    coordinates: { lat: 6.4310, lng: 3.4320 },
    nearestSafeZoneId: 'sz-6',
    isPopularDropoff: true,
  },
  {
    id: 'loc-vi-adeola',
    name: 'Victoria Island (Adeola Odeku / Civic Center)',
    area: 'Victoria Island',
    coordinates: { lat: 6.4350, lng: 3.4280 },
    nearestSafeZoneId: 'sz-6',
    isPopularDropoff: true,
  },
  {
    id: 'loc-vi-danmole',
    name: 'Victoria Island (Danmole / Access Bank HQ)',
    area: 'Victoria Island',
    coordinates: { lat: 6.4290, lng: 3.4285 },
    nearestSafeZoneId: 'sz-6',
    isPopularDropoff: true,
  },
  {
    id: 'loc-falomo',
    name: 'Ikoyi (Falomo Roundabout / Bourdillon)',
    area: 'Ikoyi',
    coordinates: { lat: 6.4460, lng: 3.4350 },
    nearestSafeZoneId: 'sz-5',
    isPopularDropoff: true,
  },
  {
    id: 'loc-kingsway',
    name: 'Ikoyi (Alfred Rewane / Kingsway Road)',
    area: 'Ikoyi',
    coordinates: { lat: 6.4530, lng: 3.4400 },
    nearestSafeZoneId: 'sz-5',
    isPopularDropoff: true,
  },
  {
    id: 'loc-marina-cms',
    name: 'Marina Terminal (CMS Bus Stop / Ferry Jetty)',
    area: 'Marina / Lagos Island',
    coordinates: { lat: 6.4530, lng: 3.3958 },
    nearestSafeZoneId: 'sz-6',
    isPopularDropoff: true,
  },
  {
    id: 'loc-broad-street',
    name: 'Broad Street Financial District',
    area: 'Marina / Lagos Island',
    coordinates: { lat: 6.4545, lng: 3.3910 },
    nearestSafeZoneId: 'sz-6',
    isPopularDropoff: true,
  },
  {
    id: 'loc-landmark-beach',
    name: 'Landmark Beach / Shiro / Hard Rock Cafe',
    area: 'Water Corporation Dr, Oniru',
    coordinates: { lat: 6.4250, lng: 3.4470 },
    nearestSafeZoneId: 'sz-5',
    isPopularDropoff: true,
  },
  {
    id: 'loc-lekki1-circa',
    name: 'Lekki Phase 1 (Admiralty Way / Circa)',
    area: 'Lekki Phase 1',
    coordinates: { lat: 6.4480, lng: 3.4720 },
    nearestSafeZoneId: 'sz-4',
    isPopularDropoff: true,
  },
  {
    id: 'loc-terra-kulture',
    name: 'Terra Kulture & Filmhouse IMAX',
    area: 'Victoria Island / Lekki',
    coordinates: { lat: 6.4315, lng: 3.4250 },
    nearestSafeZoneId: 'sz-6',
    isPopularDropoff: true,
  },
  {
    id: 'loc-seedspace-vi',
    name: 'Seedspace / Workstation Coworking Hub',
    area: 'Victoria Island',
    coordinates: { lat: 6.4320, lng: 3.4290 },
    nearestSafeZoneId: 'sz-6',
    isPopularDropoff: true,
  },
];

export const defaultCommuteRoute: CommuteRoute = {
  origin: 'Ajah Jubilee Bridge / Langbasa',
  originCoords: { lat: 6.4678, lng: 3.5683 },
  destination: 'Victoria Island (Adeola Odeku / Civic Center)',
  destinationCoords: { lat: 6.4350, lng: 3.4280 },
  distanceKm: 26.5,
  estimatedMinutes: 45,
  recommendedFuelSplitNgn: 1600,
};

export const mockCorridorDrivers: CorridorDriver[] = [
  {
    id: 'driver-107',
    name: 'Damilola Fashola',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=400&q=80',
    employer: 'Creative Lead @ Studio Yellow',
    employer_domain: 'yellowstudio.ng',
    alumni: 'University of Lagos',
    rating: 4.97,
    trips_completed: 78,
    vehicle: {
      make: 'Mercedes-Benz',
      model: 'GLA 250',
      year: 2022,
      color: 'Polar White',
      plate_number: 'LSR-210-DK',
      category: 'suv',
      drivetrain: 'FWD',
      has_ac: true,
    },
    corridor: {
      origin: 'Ajah / Lekki Phase 1',
      destination: 'Victoria Island (Adeola Odeku / Civic Center)',
      departure_time: '08:30 AM',
      available_seats: 3,
      fuel_split_ngn: 1500,
      ac_included: true,
      distance_km: 22.5,
    },
    vibe_tags: ['Morning Commute', 'Design & Brand', 'Great Convo'],
    trip_type: 'morning',
    trip_purpose: 'Heading to Victoria Island for design agency client review',
    conversation_vibe: 'Open to Chat & Brainstorm',
    ride_mood: 'chat',
    mutual_spark: 'Both in Tech & Design',
    talk_about: ['#BrandDesign', '#LagosStartups', '#Afrobeats'],
    cabin_passengers: [
      {
        id: 'p1',
        name: 'Tiwa Sowande',
        role: 'Design Lead',
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
        seatNumber: 1,
      },
    ],
    interests: ['Afrobeats', 'Design & Art', 'Startups', 'Coffee'],
    music_vibe: 'Kabza De Small, Focalistic, Wizkid',
    social_handle: '@dami_creative',
    linkedin_handle: 'damilola-fashola',
  },
  {
    id: 'driver-101',
    name: 'Babatunde Adeleke',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    employer: 'Flutterwave',
    employer_domain: 'flutterwavego.com',
    alumni: 'Babcock University',
    rating: 4.95,
    trips_completed: 142,
    vehicle: {
      make: 'Toyota',
      model: 'Camry',
      year: 2021,
      color: 'Midnight Black',
      plate_number: 'APP-842-EY',
      category: 'sedan',
      drivetrain: 'FWD',
      has_ac: true,
    },
    corridor: {
      origin: 'Ajah Langbasa',
      destination: 'Victoria Island (Ademola Adetokunbo)',
      departure_time: '07:15 AM',
      available_seats: 3,
      fuel_split_ngn: 1500,
      ac_included: true,
      distance_km: 26.5,
    },
    vibe_tags: ['AC On', 'Easy Flow', 'FinTech Talk'],
    trip_type: 'morning',
    trip_purpose: 'Morning run to Flutterwave HQ for engineering sync',
    conversation_vibe: 'Light Banter & Good Music',
    ride_mood: 'easy',
    mutual_spark: 'FinTech & Engineering Circle',
    talk_about: ['#FinTech', '#SystemArchitecture', '#Formula1'],
    cabin_passengers: [
      {
        id: 'p2',
        name: 'Amara Nwosu',
        role: 'Architect',
        avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80',
        seatNumber: 1,
      },
    ],
    interests: ['FinTech', 'Afrobeats', 'Formula 1', 'Startups'],
    music_vibe: 'Asake, Burna Boy, Rema',
    social_handle: '@babatunde_ad',
    linkedin_handle: 'babatunde-adeleke',
  },
  {
    id: 'driver-109',
    name: 'Segun Balogun',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80',
    employer: 'Full-stack Engineer @ Paystack',
    employer_domain: 'paystack.com',
    alumni: 'Covenant University',
    rating: 4.94,
    trips_completed: 94,
    vehicle: {
      make: 'Toyota',
      model: 'RAV4',
      year: 2021,
      color: 'Magnetic Gray',
      plate_number: 'SMK-491-BD',
      category: 'suv',
      drivetrain: 'AWD',
      has_ac: true,
    },
    corridor: {
      origin: 'Jakande Roundabout / Circle Mall',
      destination: 'Seedspace / Workstation Coworking Hub',
      departure_time: 'Leaving in 25m',
      available_seats: 3,
      fuel_split_ngn: 1200,
      ac_included: true,
      distance_km: 19.5,
    },
    vibe_tags: ['Leaving Soon', 'Tech Sprint', 'Coffee Run'],
    trip_type: 'leaving_now',
    trip_purpose: 'Leaving now for afternoon meetings at Seedspace VI',
    conversation_vibe: 'Casual Tech Banter',
    ride_mood: 'chat',
    mutual_spark: 'Both in Engineering',
    talk_about: ['#FullStack', '#AI', '#CoffeeCulture'],
    cabin_passengers: [],
    interests: ['Tech & AI', 'Coffee Culture', 'Crypto', 'EPL Football'],
    music_vibe: 'Lo-Fi Beats & Instrumental Soul',
    social_handle: '@segun_builds',
    linkedin_handle: 'segun-balogun',
  },
  {
    id: 'driver-108',
    name: 'Kemi Cole',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=400&q=80',
    employer: 'Film Producer & Podcaster',
    employer_domain: 'nollywoodpod.co',
    alumni: 'Pan-Atlantic University',
    rating: 4.99,
    trips_completed: 116,
    vehicle: {
      make: 'Range Rover',
      model: 'Evoque',
      year: 2023,
      color: 'Bronze Satin',
      plate_number: 'KRD-884-AC',
      category: 'suv',
      drivetrain: 'AWD',
      has_ac: true,
    },
    corridor: {
      origin: 'Chevron Drive / Alternative',
      destination: 'Terra Kulture & Filmhouse IMAX',
      departure_time: '11:30 AM',
      available_seats: 2,
      fuel_split_ngn: 1500,
      ac_included: true,
      distance_km: 22.0,
    },
    vibe_tags: ['Anytime Ride', 'Media & Arts', 'Deep Convos'],
    trip_type: 'flexible',
    trip_purpose: 'Headed to Victoria Island for film production roundtable',
    conversation_vibe: 'Deep Convos & Insights',
    ride_mood: 'chat',
    mutual_spark: 'Pan-Atlantic Alumni',
    talk_about: ['#Cinema', '#Podcasting', '#LagosCulture'],
    cabin_passengers: [
      {
        id: 'p3',
        name: 'Kunle A.',
        role: 'Data Analyst',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
        seatNumber: 1,
      },
    ],
    interests: ['Cinema & Film', 'Podcasts', 'Literature', 'Afro-Soul'],
    music_vibe: 'Asa, Omah Lay, Odumodublvck',
    social_handle: '@kemicole',
    linkedin_handle: 'kemi-cole',
  },
  {
    id: 'driver-102',
    name: 'Chioma Okonkwo',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    employer: 'PwC Nigeria',
    employer_domain: 'pwc.com',
    alumni: 'University of Lagos',
    rating: 4.98,
    trips_completed: 89,
    vehicle: {
      make: 'Honda',
      model: 'CR-V',
      year: 2022,
      color: 'Deep Purple',
      plate_number: 'KJA-512-AB',
      category: 'suv',
      drivetrain: 'AWD',
      has_ac: true,
    },
    corridor: {
      origin: 'Sangotedo (Shoprite)',
      destination: 'Marina / CMS',
      departure_time: '06:15 AM',
      available_seats: 2,
      fuel_split_ngn: 2500,
      ac_included: true,
      distance_km: 32.0,
    },
    vibe_tags: ['Quiet Ride', 'Finance & Audit', 'Smooth Drive'],
    trip_type: 'morning',
    trip_purpose: 'Morning audit engagement at Marina financial district',
    conversation_vibe: 'Peaceful & Respectful Silence',
    ride_mood: 'quiet',
    mutual_spark: 'UNILAG Alumni',
    talk_about: ['#Consulting', '#FinancialAudit', '#Books'],
    cabin_passengers: [
      {
        id: 'p4',
        name: 'Ngozi E.',
        role: 'Corporate Counsel',
        avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=120&auto=format&fit=crop&q=80',
        seatNumber: 1,
      },
    ],
    interests: ['Finance', 'Travel', 'R&B Music', 'Entrepreneurship'],
    music_vibe: 'Tems, Ayra Starr, Gospel Chill',
    social_handle: '@chioma_o',
    linkedin_handle: 'chioma-okonkwo',
  },
  {
    id: 'driver-110',
    name: 'Chidi Okafor',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&q=80',
    employer: 'Sound Engineer & Producer',
    employer_domain: 'islandevents.ng',
    alumni: 'University of Ibadan',
    rating: 4.96,
    trips_completed: 162,
    vehicle: {
      make: 'Lexus',
      model: 'RX 350',
      year: 2021,
      color: 'Obsidian Black',
      plate_number: 'EKY-771-XP',
      category: 'suv',
      drivetrain: 'AWD',
      has_ac: true,
    },
    corridor: {
      origin: 'VGC Main Gate',
      destination: 'Lekki Phase 1 (Admiralty Way)',
      departure_time: '06:45 PM',
      available_seats: 3,
      fuel_split_ngn: 1600,
      ac_included: true,
      distance_km: 24.0,
    },
    vibe_tags: ['Evening Return', 'Great Audio', 'Creative Meetup'],
    trip_type: 'evening',
    trip_purpose: 'Evening industry meetup & dinner on Admiralty Way',
    conversation_vibe: 'Easy Flow & Good Tracks',
    ride_mood: 'easy',
    mutual_spark: 'Both Island Bound',
    talk_about: ['#LiveAudio', '#EventProduction', '#AfroHouse'],
    cabin_passengers: [],
    interests: ['Audio Engineering', 'Live Music', 'Culinary', 'Afro-House'],
    music_vibe: 'Major League DJz, Burna Boy, Runtown',
    social_handle: '@chidi_vibes',
    linkedin_handle: 'chidi-okafor',
  },
  {
    id: 'driver-103',
    name: 'Tunde Balogun',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    employer: 'Kuda Technologies',
    employer_domain: 'kuda.com',
    alumni: 'Covenant University',
    rating: 4.92,
    trips_completed: 215,
    vehicle: {
      make: 'Hyundai',
      model: 'Tucson',
      year: 2020,
      color: 'Graphite Grey',
      plate_number: 'LND-399-FX',
      category: 'suv',
      drivetrain: 'FWD',
      has_ac: true,
    },
    corridor: {
      origin: 'VGC Main Gate',
      destination: 'Marina / Broad St',
      departure_time: '07:00 AM',
      available_seats: 3,
      fuel_split_ngn: 1800,
      ac_included: true,
      distance_km: 22.4,
    },
    vibe_tags: ['AC On', 'Podcasts', 'Luggage Space'],
    trip_type: 'morning',
    trip_purpose: 'Daily engineering sync at Kuda Marina',
    conversation_vibe: 'Podcast & Tech Chat',
    ride_mood: 'easy',
    mutual_spark: 'Shared Fintech Circle',
    talk_about: ['#FinTech', '#Podcasts', '#Books', '#EPL'],
    cabin_passengers: [],
    interests: ['FinTech', 'Podcasts', 'Books', 'EPL'],
    music_vibe: 'Acquired Podcast, The Diary of a CEO',
    social_handle: '@tunde_kuda',
    linkedin_handle: 'tunde-balogun',
  },
  {
    id: 'driver-104',
    name: 'Amara Nwosu',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=400&q=80',
    employer: 'Access Bank',
    employer_domain: 'accessbankplc.com',
    alumni: 'Pan-Atlantic University',
    rating: 4.99,
    trips_completed: 178,
    vehicle: {
      make: 'Mazda',
      model: 'CX-5',
      year: 2023,
      color: 'Soul Red',
      plate_number: 'EPE-812-BD',
      category: 'suv',
      drivetrain: 'AWD',
      has_ac: true,
    },
    corridor: {
      origin: 'Ikota Shopping Complex',
      destination: 'Victoria Island (Adeola Odeku)',
      departure_time: '06:30 AM',
      available_seats: 2,
      fuel_split_ngn: 2200,
      ac_included: true,
      distance_km: 19.8,
    },
    vibe_tags: ['AC On', 'FinTech Enthusiast', 'No Smoking'],
    trip_type: 'commute',
    trip_purpose: 'Strategy committee meeting at Access Bank HQ',
    conversation_vibe: 'Great Banter',
    interests: ['Banking', 'Fashion', 'Afrobeats', 'Tennis'],
    music_vibe: 'Fireboy DML, Tems, Bnxn',
    social_handle: '@amara_nwosu',
  },
  {
    id: 'driver-105',
    name: 'Babatunde Adeleke',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    employer: 'Flutterwave',
    employer_domain: 'flutterwavego.com',
    alumni: 'Babcock University',
    rating: 4.95,
    trips_completed: 142,
    vehicle: {
      make: 'Toyota',
      model: 'Camry',
      year: 2021,
      color: 'Midnight Black',
      plate_number: 'APP-842-EY',
      category: 'sedan',
      drivetrain: 'FWD',
      has_ac: true,
    },
    corridor: {
      origin: 'Victoria Island (Ademola Adetokunbo)',
      destination: 'Ajah Langbasa',
      departure_time: '05:45 PM',
      available_seats: 3,
      fuel_split_ngn: 1800,
      ac_included: true,
      distance_km: 26.5,
    },
    vibe_tags: ['AC On', 'Evening Winddown', 'Podcasts'],
    trip_type: 'commute',
    trip_purpose: 'Evening wind-down ride back to Ajah',
    conversation_vibe: 'Chill & Relaxed',
    interests: ['FinTech', 'Podcasts', 'Afrobeats'],
    music_vibe: 'Evening chill acoustic playlists',
    social_handle: '@babatunde_ad',
  },
  {
    id: 'driver-106',
    name: 'Amara Nwosu',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=400&q=80',
    employer: 'Access Bank',
    employer_domain: 'accessbankplc.com',
    alumni: 'Pan-Atlantic University',
    rating: 4.99,
    trips_completed: 178,
    vehicle: {
      make: 'Mazda',
      model: 'CX-5',
      year: 2023,
      color: 'Soul Red',
      plate_number: 'EPE-812-BD',
      category: 'suv',
      drivetrain: 'AWD',
      has_ac: true,
    },
    corridor: {
      origin: 'Victoria Island (Adeola Odeku)',
      destination: 'Ikota / VGC Main Gate',
      departure_time: '06:15 PM',
      available_seats: 2,
      fuel_split_ngn: 2200,
      ac_included: true,
      distance_km: 19.8,
    },
    vibe_tags: ['AC On', 'Chill R&B', 'Women Preferred'],
    trip_type: 'commute',
    trip_purpose: 'Evening commute heading home to Ikota/VGC',
    conversation_vibe: 'Relaxed Chat',
    interests: ['Banking', 'Music', 'Fitness'],
    music_vibe: 'Smooth R&B and Soul',
    social_handle: '@amara_nwosu',
  },
];

export const mockEmergencyProviders: EmergencyProvider[] = [
  {
    id: 'prov-501',
    name: 'Musbau Towing & Recovery Services',
    operator_name: 'Musbau Lawal',
    operator_photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    phone: '+234 803 291 0022',
    category: 'flatbed_tow',
    rating: 4.88,
    lasdri_id: 'LASDRI/2026/TK-8910',
    plate_number: 'JJJ-109-XZ',
    truck_type: 'Hydraulic Heavy Flatbed',
    distance_km: 3.4,
    traffic_eta_minutes: 14,
    flat_quote_ngn: 35000,
    equipment: ['Hydraulic Winch', 'Wheel Straps', 'OBD2 Scanner'],
    has_lasdri_verified: true,
    has_obd2_scanner: true,
    vehicle: { category: 'flatbed_tow' },
  },
  {
    id: 'prov-502',
    name: 'FastFix Mobile Bike Mechanic',
    operator_name: 'Sunday Kingsley',
    operator_photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    phone: '+234 812 400 9911',
    category: 'mechanic_bike',
    rating: 4.92,
    lasdri_id: 'LASDRI/2026/MC-4412',
    plate_number: 'EPE-441-QC',
    truck_type: 'Tooling Motorbike',
    distance_km: 1.8,
    traffic_eta_minutes: 8,
    flat_quote_ngn: 8000,
    equipment: ['Jumpstarter Battery Pack', '12V Tyre Inflator', 'OBD2 Scanner', 'Standard Tooling'],
    has_lasdri_verified: true,
    has_obd2_scanner: true,
    vehicle: { category: 'mechanic_bike' },
  },
  {
    id: 'prov-503',
    name: 'Lekki Toll Heavy Duty Rescue',
    operator_name: 'Chinedu Eze',
    operator_photo: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=400&q=80',
    phone: '+234 802 888 1234',
    category: 'wheel_lift_tow',
    rating: 4.75,
    lasdri_id: 'LASDRI/2026/TK-5120',
    plate_number: 'KJA-892-LM',
    truck_type: 'Wheel-Lift Underlift Tow',
    distance_km: 4.1,
    traffic_eta_minutes: 19,
    flat_quote_ngn: 28000,
    equipment: ['Wheel-Lift Boom', 'Safety Chains', 'Compressor'],
    has_lasdri_verified: true,
    has_obd2_scanner: false,
    vehicle: { category: 'wheel_lift_tow' },
  },
  {
    id: 'prov-504',
    name: 'Apex Radiator & Thermal Mobile Tech',
    operator_name: 'Rasheed Adebisi',
    operator_photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80',
    phone: '+234 814 332 9001',
    category: 'mechanic_bike',
    rating: 4.96,
    lasdri_id: 'LASDRI/2026/MC-9118',
    plate_number: 'AGL-220-GH',
    truck_type: 'Mobile Thermal Van',
    distance_km: 2.2,
    traffic_eta_minutes: 11,
    flat_quote_ngn: 12000,
    equipment: ['Coolant Pressure Tester', 'Heavy Duty Coolant 5L', 'OBD2 Scanner', 'Fan Relay Kit'],
    has_lasdri_verified: true,
    has_obd2_scanner: true,
    vehicle: { category: 'mechanic_bike' },
  },
];

export const mockCorridorRiders: WaitingRider[] = [
  {
    id: 'rider-206',
    name: 'Tiwa Sowande',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    employer: 'Design Lead @ Flutterwave',
    employer_domain: 'flutterwavego.com',
    rating: 4.98,
    pickupSafeZone: mockSafeZones[1], // Circle Mall
    destination: 'Victoria Island (Adeola Odeku)',
    departure_time: '08:15 AM',
    bidNgn: 1500,
    isFemaleOnly: false,
    notes: 'Heading to design sprint with agency team in VI. Laptop only.',
    status: 'waiting',
    trip_type: 'morning',
    trip_purpose: 'Design sprint with creative agency team in VI',
    conversation_vibe: 'Open to Chat & Brainstorm',
    ride_mood: 'chat',
    mutual_spark: 'Design & Product Circle',
    talk_about: ['#Design', '#Branding', '#Afrobeats'],
    interests: ['Design', 'Afrobeats', 'Startups', 'Brunch'],
    social_handle: '@tiwasowande',
    linkedin_handle: 'tiwa-sowande',
  },
  {
    id: 'rider-207',
    name: 'Kunle Adeyemi',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80',
    employer: 'Indie Hacker & Mobile Dev',
    employer_domain: 'buildinpublic.ng',
    rating: 4.95,
    pickupSafeZone: mockSafeZones[0], // TotalEnergies Jakande
    destination: 'Seedspace / Workstation Coworking Hub',
    departure_time: 'Leaving in 20m',
    bidNgn: 1400,
    isFemaleOnly: false,
    notes: 'Afternoon sprint session at Seedspace VI. Backpack only.',
    status: 'waiting',
    trip_type: 'leaving_now',
    trip_purpose: 'Afternoon sprint & product demo day prep',
    conversation_vibe: 'Tech Banter & Chill',
    ride_mood: 'easy',
    mutual_spark: 'Mobile Dev & Indie Hacking',
    talk_about: ['#AI', '#TypeScript', '#CoffeeCulture'],
    interests: ['Tech & AI', 'Coffee', 'Startups', 'Gaming'],
    social_handle: '@kunle_codes',
    linkedin_handle: 'kunle-codes',
  },
  {
    id: 'rider-208',
    name: 'Seyi Balogun',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
    employer: 'Brand Consultant',
    employer_domain: 'islandstyle.ng',
    rating: 4.96,
    pickupSafeZone: mockSafeZones[2], // VGC Main Gate
    destination: 'Lekki Phase 1 (Admiralty Way)',
    departure_time: '06:30 PM',
    bidNgn: 2000,
    isFemaleOnly: false,
    notes: 'Brand consultation meeting on Admiralty Way.',
    status: 'waiting',
    trip_type: 'evening',
    trip_purpose: 'Brand consultation meeting on Admiralty Way',
    conversation_vibe: 'Great Banter',
    ride_mood: 'chat',
    mutual_spark: 'Both in Creative Sector',
    talk_about: ['#Fashion', '#CreativeStrategy', '#LagosArt'],
    interests: ['Fashion', 'Live Music', 'Culinary', 'Art'],
    social_handle: '@seyi_style',
    linkedin_handle: 'seyi-balogun',
  },
  {
    id: 'rider-201',
    name: 'Chioma Okoli',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    employer: 'Stanbic IBTC Bank',
    employer_domain: 'stanbicibtc.com',
    rating: 4.97,
    pickupSafeZone: mockSafeZones[1], // Circle Mall
    destination: 'Victoria Island (Ahmadu Bello Way)',
    departure_time: '06:45 AM',
    bidNgn: 2000,
    isFemaleOnly: false,
    notes: 'Heading to Stanbic HQ. Quiet rider, backpack only.',
    status: 'waiting',
    trip_type: 'commute',
    trip_purpose: 'Morning corporate commute to Stanbic IBTC',
    conversation_vibe: 'Quiet & Relaxed',
    interests: ['Finance', 'Podcasts', 'Wellness'],
    social_handle: '@chioma_ibtc',
  },
  {
    id: 'rider-202',
    name: 'Olumide Adeleke',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    employer: 'Flutterwave',
    employer_domain: 'flutterwavego.com',
    rating: 4.93,
    pickupSafeZone: mockSafeZones[0], // TotalEnergies Jakande
    destination: 'Marina / Broad St',
    departure_time: '07:00 AM',
    bidNgn: 1800,
    isFemaleOnly: false,
    notes: 'Laptop bag only. Work at Flutterwave engineering.',
    status: 'waiting',
    trip_type: 'commute',
    trip_purpose: 'Engineering sprint at Flutterwave Marina',
    conversation_vibe: 'Tech Banter & Chill',
    interests: ['FinTech', 'Gaming', 'Afrobeats'],
    social_handle: '@olumide_dev',
  },
  {
    id: 'rider-203',
    name: 'Amina Bello',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=400&q=80',
    employer: 'KPMG Nigeria',
    employer_domain: 'kpmg.com',
    rating: 4.99,
    pickupSafeZone: mockSafeZones[2], // VGC Main Gate
    destination: 'Victoria Island (Ademola Adetokunbo)',
    departure_time: '06:30 AM',
    bidNgn: 2200,
    isFemaleOnly: true,
    notes: 'Senior Consultant at KPMG. Early morning commute.',
    status: 'waiting',
    trip_type: 'commute',
    trip_purpose: 'Management consulting client briefing at KPMG VI',
    conversation_vibe: 'Chill & Meaningful',
    interests: ['Strategy', 'Books', 'Yoga'],
    social_handle: '@amina_bello',
  },
  {
    id: 'rider-204',
    name: 'David Nwachukwu',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    employer: 'Dangote Group',
    employer_domain: 'dangote.com',
    rating: 4.88,
    pickupSafeZone: mockSafeZones[3], // Mobil Sandfill
    destination: 'Marina / CMS Outer Marina',
    departure_time: '07:15 AM',
    bidNgn: 1500,
    isFemaleOnly: false,
    notes: 'Corporate colleague at Dangote Marina office.',
    status: 'waiting',
    trip_type: 'commute',
    trip_purpose: 'Group operations review at Dangote Marina',
    conversation_vibe: 'Casual Banter',
    interests: ['Logistics', 'Football', 'Afrobeats'],
    social_handle: '@david_nw',
  },
  {
    id: 'rider-205',
    name: 'Zainab Yusuf',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    employer: 'PwC Nigeria',
    employer_domain: 'pwc.com',
    rating: 4.96,
    pickupSafeZone: mockSafeZones[4], // Palms Shopping Mall
    destination: 'Victoria Island (Adeola Odeku)',
    departure_time: '06:40 AM',
    bidNgn: 2000,
    isFemaleOnly: false,
    notes: 'Senior associate at PwC. Looking for AC ride.',
    status: 'waiting',
    trip_type: 'commute',
    trip_purpose: 'Morning tax advisory team meeting at PwC',
    conversation_vibe: 'Chill & Relaxed',
    interests: ['Tax', 'Travel', 'R&B'],
    social_handle: '@zainab_y',
  },
];

export const mockTrafficAlerts: TrafficAlert[] = [
  {
    id: 'alert-1',
    location: 'Lekki 1st Toll',
    status: 'heavy',
    delayMinutes: 20,
    message: 'Heavy bottleneck approaching Admiralty Toll; expect 20m slowdown.',
  },
  {
    id: 'alert-2',
    location: 'Sandfill Bus Stop',
    status: 'free_flow',
    delayMinutes: 0,
    message: 'Sandfill underpass clear and moving smoothly.',
  },
  {
    id: 'alert-3',
    location: 'Jakande Roundabout',
    status: 'free_flow',
    delayMinutes: 0,
    message: 'Road surface dry, zero flash flood ponding.',
  },
];
