// Mock Everyday Street Carpool Rides & Lagos Street Locations
import { StreetCarpoolRide, StreetLocation, NeighborhoodRider } from './types';

export const mockStreetLocations: StreetLocation[] = [
  {
    id: 'st-admiralty',
    name: 'Admiralty Way, Lekki Phase 1',
    area: 'Lekki Phase 1',
    coordinates: { lat: 6.4480, lng: 3.4720 },
    popularNearbySpots: ["Sailor's Lounge", 'Circa Lagos', 'The Place Admiralty'],
  },
  {
    id: 'st-freedom-way',
    name: 'Freedom Way, Lekki Phase 1',
    area: 'Lekki Phase 1',
    coordinates: { lat: 6.4390, lng: 3.4830 },
    popularNearbySpots: ['The Dome', 'Orange Island Gate', 'Filmhouse IMAX'],
  },
  {
    id: 'st-fola-osibo',
    name: 'Fola Osibo Street, Lekki Phase 1',
    area: 'Lekki Phase 1',
    coordinates: { lat: 6.4445, lng: 3.4650 },
    popularNearbySpots: ['Sweet Sensation', 'Ebeano Supermarket'],
  },
  {
    id: 'st-chevron',
    name: 'Chevron Drive, Lekki',
    area: 'Chevron / Lekki',
    coordinates: { lat: 6.4485, lng: 3.5385 },
    popularNearbySpots: ['Atlantic View Estate', 'Chevron HQ Gate', 'Drive-In Plaza'],
  },
  {
    id: 'st-orchid',
    name: 'Orchid Road, Lafiaji',
    area: 'Orchid / Lekki',
    coordinates: { lat: 6.4410, lng: 3.5520 },
    popularNearbySpots: ['Eleganza Bus Stop', 'Orchid Hotel', 'Lakeview Estate'],
  },
  {
    id: 'st-agungi',
    name: 'Agungi Road & Bus Stop',
    area: 'Agungi / Lekki',
    coordinates: { lat: 6.4395, lng: 3.5012 },
    popularNearbySpots: ['Faith City', 'Bakers World', 'Agungi Central'],
  },
  {
    id: 'st-osapa',
    name: 'Osapa London Main Street',
    area: 'Osapa / Lekki',
    coordinates: { lat: 6.4430, lng: 3.5090 },
    popularNearbySpots: ['Canal West Gate', 'Cardinale Supermarket'],
  },
  {
    id: 'st-vgc',
    name: 'VGC Main Gate & Park',
    area: 'Victoria Garden City',
    coordinates: { lat: 6.4552, lng: 3.5594 },
    popularNearbySpots: ['VGC Club', 'VGC Gate Security Bay'],
  },
  {
    id: 'st-bourdillon',
    name: 'Bourdillon Road, Ikoyi',
    area: 'Ikoyi',
    coordinates: { lat: 6.4510, lng: 3.4390 },
    popularNearbySpots: ['Falomo Roundabout', 'Glover Memorial'],
  },
  {
    id: 'st-adeola-odeku',
    name: 'Adeola Odeku Street, VI',
    area: 'Victoria Island',
    coordinates: { lat: 6.4350, lng: 3.4280 },
    popularNearbySpots: ['Civic Center', 'Zenith Bank HQ', 'Spar VI'],
  },
  {
    id: 'st-bode-thomas',
    name: 'Bode Thomas Street, Surulere',
    area: 'Surulere',
    coordinates: { lat: 6.4950, lng: 3.3550 },
    popularNearbySpots: ['Adeniran Ogunsanya Mall', 'Masha Roundabout'],
  },
  {
    id: 'st-herbert-macaulay',
    name: 'Herbert Macaulay Way, Yaba',
    area: 'Yaba',
    coordinates: { lat: 6.5090, lng: 3.3790 },
    popularNearbySpots: ['Yaba Tech Hubs', 'Sabo Market', 'Unilag Road'],
  },
  {
    id: 'st-isaac-john',
    name: 'Isaac John Street, Ikeja GRA',
    area: 'Ikeja GRA',
    coordinates: { lat: 6.5910, lng: 3.3590 },
    popularNearbySpots: ['Radisson Blu Ikeja', 'R-Jolad Hospital', 'Sheraton'],
  },
];

export const mockEverydayRides: StreetCarpoolRide[] = [
  {
    id: 'ride-admiralty-vi',
    driverId: 'driver-101',
    driverName: 'Babatunde Adeleke',
    driverAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    driverRole: 'Senior FinTech PM @ Interswitch',
    driverRating: 4.96,
    driverTrips: 112,
    vehicle: {
      make: 'Toyota',
      model: 'Camry',
      color: 'Midnight Black',
      plateNumber: 'APP-842-EY',
      hasAc: true,
    },
    originStreet: 'Admiralty Way, Lekki Phase 1',
    originCoords: { lat: 6.4480, lng: 3.4720 },
    destination: 'Victoria Island (Adeola Odeku / Civic Center)',
    destinationCoords: { lat: 6.4350, lng: 3.4280 },
    routePath: [
      [6.4480, 3.4720],
      [6.4445, 3.4650],
      [6.4420, 3.4530],
      [6.4460, 3.4350],
      [6.4390, 3.4300],
      [6.4350, 3.4280],
    ],
    departureDay: 'Today',
    departureTime: 'Leaving in 12 mins (2:30 PM)',
    departureCategory: 'leaving_now',
    availableSeats: 2,
    totalSeats: 3,
    fuelSplitNgn: 1500,
    pickupWalkMinutes: 2,
    pickupStreetCorner: 'Corner of Admiralty Way & Fola Osibo',
    status: 'active',
    cabinPassengers: [
      {
        id: 'cp-1',
        name: 'Toluwani A.',
        role: 'Brand Lead',
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
        seatNumber: 1,
      },
    ],
    interests: ['Tech', 'FinTech', 'Afrobeats', 'Podcasts'],
    linkedinHandle: 'babatunde-adeleke',
    passesNearUser: true,
  },
  {
    id: 'ride-chevron-landmark',
    driverId: 'driver-107',
    driverName: 'Damilola Fashola',
    driverAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=400&q=80',
    driverRole: 'Creative Lead @ Studio Yellow',
    driverRating: 4.98,
    driverTrips: 78,
    vehicle: {
      make: 'Mercedes-Benz',
      model: 'GLA 250',
      color: 'Polar White',
      plateNumber: 'LSR-210-DK',
      hasAc: true,
    },
    originStreet: 'Chevron Drive, Lekki',
    originCoords: { lat: 6.4485, lng: 3.5385 },
    destination: 'Landmark Beach / Hard Rock Cafe, Oniru',
    destinationCoords: { lat: 6.4250, lng: 3.4470 },
    routePath: [
      [6.4485, 3.5385],
      [6.4428, 3.5186],
      [6.4395, 3.5012],
      [6.4372, 3.4750],
      [6.4360, 3.4610],
      [6.4312, 3.4510],
      [6.4250, 3.4470],
    ],
    departureDay: 'Today',
    departureTime: 'Today at 5:45 PM',
    departureCategory: 'today',
    availableSeats: 3,
    totalSeats: 4,
    fuelSplitNgn: 2000,
    pickupWalkMinutes: 3,
    pickupStreetCorner: 'Chevron Drive Roundabout by Atlantic View Gate',
    status: 'active',
    interests: ['Design', 'Music', 'Beach Hangouts', 'Startups'],
    linkedinHandle: 'damilola-fashola',
    passesNearUser: true,
  },
  {
    id: 'ride-freedom-ikeja',
    driverId: 'driver-102',
    driverName: 'Chioma Okonjo',
    driverAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    driverRole: 'Growth Lead @ Piggyvest',
    driverRating: 4.95,
    driverTrips: 84,
    vehicle: {
      make: 'Hyundai',
      model: 'Tucson',
      color: 'Silver',
      plateNumber: 'KSF-782-AA',
      hasAc: true,
    },
    originStreet: 'Freedom Way, Lekki Phase 1',
    originCoords: { lat: 6.4390, lng: 3.4830 },
    destination: 'Ikeja City Mall / Allen Avenue',
    destinationCoords: { lat: 6.6020, lng: 3.3510 },
    routePath: [
      [6.4390, 3.4830],
      [6.4420, 3.4530],
      [6.4530, 3.3958],
      [6.5090, 3.3790],
      [6.5520, 3.3870],
      [6.6020, 3.3510],
    ],
    departureDay: 'Saturday',
    departureTime: 'Saturday at 11:00 AM (Weekend Trip)',
    departureCategory: 'weekend',
    availableSeats: 2,
    totalSeats: 3,
    fuelSplitNgn: 2500,
    pickupWalkMinutes: 4,
    pickupStreetCorner: 'Freedom Way junction by Orange Island turnoff',
    status: 'active',
    cabinPassengers: [
      {
        id: 'cp-2',
        name: 'Zainab A.',
        role: 'Data Analyst',
        avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80',
        seatNumber: 1,
      },
    ],
    interests: ['Fintech', 'Shopping', 'Afrobeats', 'Book Club'],
    linkedinHandle: 'chioma-okonjo',
    passesNearUser: true,
  },
  {
    id: 'ride-vgc-marina',
    driverId: 'driver-103',
    driverName: 'Dr. Olumide Balogun',
    driverAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    driverRole: 'Consultant @ Lagoon Hospital',
    driverRating: 4.99,
    driverTrips: 154,
    vehicle: {
      make: 'Honda',
      model: 'Accord',
      color: 'Graphite Grey',
      plateNumber: 'BDG-451-EZ',
      hasAc: true,
    },
    originStreet: 'VGC Main Gate & Park',
    originCoords: { lat: 6.4552, lng: 3.5594 },
    destination: 'Marina Financial District / CMS',
    destinationCoords: { lat: 6.4530, lng: 3.3958 },
    routePath: [
      [6.4552, 3.5594],
      [6.4485, 3.5385],
      [6.4428, 3.5186],
      [6.4395, 3.5012],
      [6.4312, 3.4510],
      [6.4460, 3.4350],
      [6.4530, 3.3958],
    ],
    departureDay: 'Sunday',
    departureTime: 'Sunday at 9:15 AM (Morning Service / Outing)',
    departureCategory: 'weekend',
    availableSeats: 3,
    totalSeats: 3,
    fuelSplitNgn: 1800,
    pickupWalkMinutes: 2,
    pickupStreetCorner: 'VGC Main Gate Security Bay',
    status: 'active',
    interests: ['Medicine', 'Classical Music', 'Current Affairs'],
    linkedinHandle: 'olumide-balogun',
    passesNearUser: true,
  },
  {
    id: 'ride-bode-vi',
    driverId: 'driver-104',
    driverName: 'Emeka Nwosu',
    driverAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=400&q=80',
    driverRole: 'Data Architect @ Flutterwave',
    driverRating: 4.92,
    driverTrips: 63,
    vehicle: {
      make: 'Toyota',
      model: 'Corolla',
      color: 'Silver Grey',
      plateNumber: 'FKJ-902-TR',
      hasAc: true,
    },
    originStreet: 'Bode Thomas Street, Surulere',
    originCoords: { lat: 6.4950, lng: 3.3550 },
    destination: 'Victoria Island (Danmole / Access Bank HQ)',
    destinationCoords: { lat: 6.4290, lng: 3.4285 },
    routePath: [
      [6.4950, 3.3550],
      [6.4850, 3.3620],
      [6.4710, 3.3750],
      [6.4530, 3.3958],
      [6.4290, 3.4285],
    ],
    departureDay: 'Today',
    departureTime: 'Today at 3:15 PM',
    departureCategory: 'today',
    availableSeats: 2,
    totalSeats: 3,
    fuelSplitNgn: 1400,
    pickupWalkMinutes: 3,
    pickupStreetCorner: 'Bode Thomas by Adeniran Ogunsanya junction',
    status: 'active',
    interests: ['Tech', 'Gaming', 'Football', 'Podcasts'],
    linkedinHandle: 'emeka-nwosu',
  },
  {
    id: 'ride-isaac-yaba',
    driverId: 'driver-105',
    driverName: 'Folake Adeleke',
    driverAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    driverRole: 'Product Lead @ Kuda Bank',
    driverRating: 4.97,
    driverTrips: 91,
    vehicle: {
      make: 'Honda',
      model: 'Civic',
      color: 'Crimson Red',
      plateNumber: 'GGE-311-TY',
      hasAc: true,
    },
    originStreet: 'Isaac John Street, Ikeja GRA',
    originCoords: { lat: 6.5910, lng: 3.3590 },
    destination: 'Herbert Macaulay Way, Yaba Tech Hubs',
    destinationCoords: { lat: 6.5090, lng: 3.3790 },
    routePath: [
      [6.5910, 3.3590],
      [6.5820, 3.3650],
      [6.5520, 3.3870],
      [6.5250, 3.3750],
      [6.5090, 3.3790],
    ],
    departureDay: 'Tomorrow',
    departureTime: 'Tomorrow at 8:15 AM',
    departureCategory: 'tomorrow',
    availableSeats: 2,
    totalSeats: 3,
    fuelSplitNgn: 1200,
    pickupWalkMinutes: 2,
    pickupStreetCorner: 'Isaac John St by Radisson Blu entrance',
    status: 'active',
    interests: ['Product Design', 'SaaS', 'Coffee', 'Afrobeats'],
    linkedinHandle: 'folake-adeleke',
  },
];

export const mockNeighborhoodRiders: NeighborhoodRider[] = [
  {
    id: 'rider-st-1',
    name: 'Toluwani Adeyemi',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    employer: 'Brand Designer @ Paystack',
    streetName: 'Admiralty Way, Lekki Phase 1',
    coordinates: { lat: 6.4470, lng: 3.4700 },
    destination: 'Victoria Island',
    departureTime: 'Around 2:30 PM',
    bidNgn: 1500,
  },
  {
    id: 'rider-st-2',
    name: 'Kelechi Okafor',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    employer: 'Frontend Dev @ Moniepoint',
    streetName: 'Fola Osibo Street, Lekki Phase 1',
    coordinates: { lat: 6.4440, lng: 3.4640 },
    destination: 'Ikeja City Mall',
    departureTime: 'Leaving now',
    bidNgn: 2000,
  },
  {
    id: 'rider-st-3',
    name: 'Zainab Bello',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80',
    employer: 'Legal Counsel @ Aluko & Oyebode',
    streetName: 'Bourdillon Road, Ikoyi',
    coordinates: { lat: 6.4515, lng: 3.4410 },
    destination: 'Marina CMS',
    departureTime: 'Around 3:00 PM',
    bidNgn: 1200,
  },
];
